# Generated by Django 4.2.1 on 2023-06-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room_test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                ("area", models.FloatField()),
                ("room_type", models.CharField(max_length=100)),
            ],
        ),
    ]
