# Generated by Django 4.2.1 on 2023-06-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_property_delete_room_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Property",
        ),
    ]
