# Generated by Django 4.2.1 on 2023-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_delete_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="area",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="rent_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
