# Generated by Django 4.2.1 on 2023-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_alter_room_area_alter_room_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="price",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
